# Generated by Django 4.0.6 on 2022-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
